name: Update hackathon results

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 */2 * * *" # every 2 hours

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout uhack repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/_data/requirements.txt

      - name: Scrape GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src/_data
          python scrape_github.py

      - name: Push new data
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.json"
          message: "🏆 update hackathon results 🏆"
          default_author: github_actions
